# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-12 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20180307_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='choices_fr',
        ),
        migrations.RemoveField(
            model_name='field',
            name='default_fr',
        ),
        migrations.RemoveField(
            model_name='field',
            name='help_text_fr',
        ),
        migrations.RemoveField(
            model_name='field',
            name='label_fr',
        ),
        migrations.RemoveField(
            model_name='field',
            name='placeholder_text_fr',
        ),
        migrations.RemoveField(
            model_name='form',
            name='button_text_fr',
        ),
        migrations.RemoveField(
            model_name='form',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='form',
            name='email_message_fr',
        ),
        migrations.RemoveField(
            model_name='form',
            name='email_subject_fr',
        ),
        migrations.RemoveField(
            model_name='form',
            name='response_fr',
        ),
    ]
