# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-12 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='value_fr',
        ),
    ]
