# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-25 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181212_1211'),
        ('blog', '0003_auto_20181227_1252'),
    ]

    operations = [
    ]
