# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-12 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_auto_20180307_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='title_fr',
        ),
    ]
