# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-17 17:30
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.pages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20180307_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='in_menus',
            field=mezzanine.pages.fields.MenusField(blank=True, choices=[(1, 'Header'), (2, 'Footer')], max_length=100, null=True, verbose_name='Show in menus'),
        ),
    ]
