# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-26 22:11
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.pages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20190703_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='in_menus',
            field=mezzanine.pages.fields.MenusField(blank=True, choices=[(1, 'Action'), (2, 'Departement'), (3, 'Footer vertical'), (4, 'Footer horizontal'), (5, 'Magazine'), (6, 'Vous êtes'), (7, 'Personnes'), (8, 'Candidacies')], max_length=100, null=True, verbose_name='Show in menus'),
        ),
    ]
