# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-03-01 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20201026_2311'),
        ('pages', '0018_auto_20191218_1522'),
    ]

    operations = [
    ]
