# Generated by Django 2.2.24 on 2021-08-23 15:53

from django.db import migrations
import mezzanine.pages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20191218_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='in_menus',
            field=mezzanine.pages.fields.MenusField(blank=True, choices=[(1, 'Header'), (2, 'Menu'), (3, 'Footer vertical'), (4, 'Footer horizontal'), (5, 'Magazine'), (6, 'Vous êtes'), (7, 'Personnes'), (8, 'Candidacies')], max_length=100, null=True, verbose_name='Show in menus'),
        ),
    ]
