# Generated by Django 3.2.18 on 2023-04-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210417_1930'),
        ('pages', '0019_auto_20210817_1431'),
        ('pages', '0019_auto_20210823_1753'),
    ]

    operations = [
    ]
