# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-12 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20180307_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='_meta_title_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='option1_fr',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='option2_fr',
        ),
    ]
