# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-22 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20180522_1459'),
        ('shop', '0012_auto_20180307_1152'),
    ]

    operations = [
    ]
