# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-01 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_merge_20181022_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='key',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
