# Generated by Django 2.2.24 on 2021-08-23 15:53

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20190703_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='featured_image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, upload_to='shop', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Sale', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='order',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='product',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=mezzanine.core.fields.FileField(max_length=255, upload_to='product', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='shop.Product'),
        ),
    ]
